### ISSUE TITLE
Auto-completion error

### ISSUE THREAD

**Issue by dzaima** [joelmoniz/REPLmode#3]
Any time the auto-completion panel has to show up it doesn't and throws this:

    java.lang.NullPointerException
	at processing.mode.java.pdex.CompletionPanel.calcWidth(CompletionPanel.java:275)
	at processing.mode.java.pdex.CompletionPanel.<init>(CompletionPanel.java:160)
	at processing.mode.java.pdex.JavaTextArea.showSuggestion(JavaTextArea.java:531)
	at processing.mode.java.pdex.JavaTextArea.lambda$1(JavaTextArea.java:340)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ChaoticLeah** [comment]
I have the same issue, hope this gets resolved soon.
